### ISSUE TITLE
Task does not show up in Kanban view, when moved to a project without a default bucket

### ISSUE THREAD

**Issue by lynnerup** [go-vikunja/vikunja#307] opened 2024-08-12 19:05 UTC
### Description

If I create a task in project A, it will automatically show up in the first bucket in the Kanban view, even if no bucket has been marked as default.

However, if I create a task in project B, and then move it to project A, then the task will not show up in the Kanban view og project A. However, it will show up in the List and Table.

It seems like when creating a new task, it will default to the first bucket, even when no default bucket has been specified. But that this does not happen during move,

This behaviour occurs when tested locally on version 0.24.1, but not in the demo site. I do not know why.

### Vikunja Version

0.24.1

### Browser and version

Google Chrome 127.0.6533.100

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment] 2024-08-12 19:24
Duplicate of https://github.com/go-vikunja/vikunja/issues/290

Also, I've [just released 0.24.2](https://vikunja.io/changelog/vikunja-v0.24.2-was-released) which contains the fix as well.

**Closed by kolaente** 2024-08-12 19:24 UTC
