### ISSUE TITLE
HTML description is badly displayed on mails

### ISSUE THREAD

**Issue by mvalois** [go-vikunja/vikunja#268] opened 2024-06-04 10:04 UTC
### Description

When receiving mail notifications about a task description change, the displayed mail contains HTML tags and is therefore hardly readable.

### Vikunja Version

0.23.0

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![Capture d’écran du 2024-06-04 12-00-42](https://github.com/go-vikunja/vikunja/assets/30313678/3970abb8-8f84-408d-8c21-8fda31e24bc3)

**Comment by kolaente** [comment] 2024-06-04 12:24
This has been fixed in 191a476823f19111e60af58ff5268756167ddc46. I was not able to reproduce it with the current main branch. How did you reproduce it on [try.vikunja.io](https://try.vikunja.io]?

**Comment by mvalois** [comment] 2024-06-05 10:11
oh sorry it was a mistake, I did not reproduced it on the demo site.

**Comment by kolaente** [comment] 2024-06-05 10:22
Then it's already fixed. You can check it with the unstable build on your installation (make a backup first)

**Closed** 2024-06-05 10:23 UTC
