### ISSUE TITLE
Smartphone UI Issues

### ISSUE THREAD

**Issue by haldi4803** [go-vikunja/vikunja#309] opened 2024-08-14 18:23 UTC
### Description

1. Filters.
When you click the Filter button a Popup comes that is bigger than my Screen, so you can scroll the Popup. On the Other hand its ALMOST impossible to close the popup again! you need to hit the 5 pixels on top between the popup and the top of the screen to close it.
There should be a [Close] button on the Filter popup if it's that big!

2. Header and Page width are not the same.
Can be seen in the Kanban Tab, or in the Gant Tab if it hasn't finished loading yet. The Default zoom can be zoomed out, and you see a white bar on the right side appearing, but the header is still going until the end. Probably because it aligns to the widest element on the page?

3. Kanban view is not FullScreen / Device width.
All other Elements properly align to Page Width. So it's beautifuly maximized. Only Kanban does NOT.
I Assume that is because of the "+ Create new Bucket" button. While that might work flawless on Desktop Mode, on the Smartphone with a Vertical Display that is an issue. The button should just not be there but somewhere else.
Don't ask me where... i'd say same heigh als "Clear Filters" and Filters" or Below that ontop of the existing Bucket? I don't know.
But on the Right side just causes issues.

### Vikunja Version

Frontend Version: 0.22.1  API Version: v0.22.1

### Browser and version

Firefox for Android v129.0

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![Screenshot_20240814-200558](https://github.com/user-attachments/assets/485131c5-5c52-4c7a-ada2-878b2c420024)
![Screenshot_20240814-200626](https://github.com/user-attachments/assets/31ea1aa1-92ff-4d2d-9656-c15fb79eec7e)
![Screenshot_20240814-200535](https://github.com/user-attachments/assets/1ec96f84-9fb6-44dc-8c03-35be45907f25)
![Screenshot_20240814-201822](https://github.com/user-attachments/assets/c62d8031-6ed5-4101-9c47-5347ea423eb0)

**Comment by haldi4803** [comment] 2024-08-15 09:16
![Screenshot_20240815-111426](https://github.com/user-attachments/assets/eae8885d-379f-4ca3-9585-b471ab4fa9e2)

Found another issue...
If you are inside an element to edit something.
How do you get back?
Only one of those two arrows bring you back. To the List.
Guess which one? IMHO both should.

**Comment by kolaente** [comment] 2024-08-26 20:00
Are these issues all the same on the latest release?

**Comment by haldi4803** [comment] 2024-08-27 11:31
Switched from TrueNas App to Docker.
Version: v0.24.2

Filters are now small. So issue 1 is solved.
![Screenshot_20240827-132935](https://github.com/user-attachments/assets/19804b0a-4a63-4cf6-a4fc-df9b198dac92)

Kannan Tab still has issues with Page Width of Header (and Filter)
![Screenshot_20240827-133010](https://github.com/user-attachments/assets/965ecd68-b904-49c3-9e73-2b723668ab13)

**Comment by kolaente** [comment] 2024-09-12 14:45
The filter and kanban issues are now fixed in https://github.com/go-vikunja/vikunja/commit/f53b93d98ae35e904dd24944722a0388421cca5e and https://github.com/go-vikunja/vikunja/commit/945f25b81858f0abb303c5bd0d6ce2612e1dbf3b. Please check that with the next unstable build.

> Header and Page width are not the same.
Can be seen in the Kanban Tab, or in the Gant Tab if it hasn't finished loading yet. The Default zoom can be zoomed out, and you see a white bar on the right side appearing, but the header is still going until the end. Probably because it aligns to the widest element on the page?

I was unable to reproduce that. Can you?

**Comment by haldi4803** [comment] 2024-09-12 18:14
Yes.
Using Firefox Mobile or Chrome.
Might be due to my Display Resolution of 1644x3840 pixel which is a strange aspect ratio?

![Screenshot_20240912-201106](https://github.com/user-attachments/assets/4f184e53-6f15-4407-8626-cdb0132ea140)

https://github.com/user-attachments/assets/7fabbdba-3e30-47eb-a736-7288583642c1

**Comment by kolaente** [comment] 2024-09-13 09:08
Looks like the fix from yesterday was actually not deployed to try, because of an issue with the build. It is now available, can you check again?

**Comment by kolaente** [comment] 2024-09-18 17:04
I'm closing as resolved, please ping if you still encounter issues with this.

**Closed by kolaente** 2024-09-18 17:04 UTC
Labels: bug
