### ISSUE TITLE
Upcoming "Today" not showing expected tasks

### ISSUE THREAD

**Issue by vinn2010** [go-vikunja/vikunja#246] opened 2024-04-04 22:21 UTC
### Description

In the Upcoming section, when I choose to see jobs by "today" the boxes become:

`from: now/d` `to:now/d+1d`

No jobs are shown.

![1day](https://github.com/go-vikunja/vikunja/assets/71597180/38fca18b-81b0-43c2-ab5d-23c02b01118d)

When I set the date range to two day, I get the expected list of jobs that are due within one day.

`from: now/d` `to:now/d+2d`

![2 days](https://github.com/go-vikunja/vikunja/assets/71597180/4e3f4aa4-a234-4ca3-a149-ed32b3301b65)

The demo instance does not show this behavior. I suspect it might be something to do with timezone.

My timezone is asia/bangkok

### Vikunja Version

v0.23.0

### Browser and version

Firefox 119.0

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment] 2024-04-05 13:56
Yeah this looks like a time zone problem. The relative time used the time zone the server runs in, not the one of the user.
There have been changes so that it uses the user's configured time zone in that case - given how you weren't able to reproduce it on try, I guess that confirms this. 

Please check with the next release (once that's released) or the latest unstable build. I'll close this now, ping again if you have issues with either the latest unstable build or the next release.

**Closed by kolaente** 2024-04-05 13:56 UTC
