### ISSUE TITLE
Cannot scroll a task card on mobile browser 

### ISSUE THREAD

**Issue by majster95** [go-vikunja/vikunja#325] opened 2024-09-14 21:20 UTC
### Description

Hi, I’ve noticed a strange behaviour of UI on mobile phone browser (iOS).

When I open a task card from kanban view on my mobile phone the UI freezes and I cannot scroll across the card, I found that when I flip my phone horizontally and try to scroll from right edge then I can do it.  I happens only from kanban view, others list views opens fine. I can reproduce the same bug on demo website. 

### Vikunja Version

Unstable 

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by kolaente** [comment] 2024-09-15 09:12
Since when is this a problem?

**Comment by majster95** [comment] 2024-09-15 09:22
It’s quite difficult to say, I installed Vikunja few days ago (and I really love it 😀) and since then I’ve been experiencing this problem.

**Comment by kolaente** [comment] 2024-09-15 10:11
There have been fixes to the mobile layout yesterday, maybe these have caused this. I thought that https://github.com/go-vikunja/vikunja/commit/6a5342bd49b53903e19ac4297312963c7dcdad32 might fix that, but does not seem to. At least with browserstack I was still able to reproduce your problem.

**Comment by majster95** [comment] 2024-09-15 10:16
Yes, problem still persists in latest build. It’s interesting that it happens only when card is being opened from Kanban view.

**Comment by kolaente** [comment] 2024-09-18 17:01
Should be fixed now in https://github.com/go-vikunja/vikunja/commit/16d73869752cea8ffcc73ee6be3021994cd6b6c1, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).

And thanks for the coffee!

**Closed** 2024-09-18 17:01 UTC
Labels: bug
