### ISSUE TITLE
Tasks are not rendered in Gantt, if start date is earlier than date range start date

### ISSUE THREAD

**Issue by Peasniped** [go-vikunja/vikunja#353] opened 2024-11-12 14:37 UTC
### Description

In the Gantt view, if the start date of a task is earlier than the start date of the selected date range, the task is not rendered in the Gantt chart. However, if the task's end date falls within the date range, the task should still be visible in the chart.

This behavior means that for long-running tasks (e.g., tasks that last two months), once the task's start date has passed, the task will no longer be displayed in the table, even if its end date falls within the visible date range.

### Vikunja Version

v0.24.4

### Browser and version

Google Chrome Version 130.0.6723.117 (Official Build) (64-bit)

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![vikunja issue](https://github.com/user-attachments/assets/84146287-f741-4d56-89cc-26e2a1cc47b0)
In the second screenshot, the start date of the date range is moved forward by one day, causing the task 'Test' to disappear.

**Comment by kolaente** [comment] 2024-11-15 11:46
Duplicate of https://github.com/go-vikunja/vikunja/issues/149

**Closed by kolaente** 2024-11-15 11:46 UTC
